# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'witneyxo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for witneyxo
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'XCDYouTubeKit', '~> 2.5'


  # target 'witneyxo-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'witneyxoTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end 

end

# target 'witneyxo-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for witneyxo-tvOS

#   target 'witneyxo-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
